# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Y.L. Zhao
email: ylzhao1996@qq.com
description: > # this means to ignore newlines until "baseurl:"
  My site is built on Nov. 24, 2019. It is used to record something I am interested in.


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xiaoke0515.github.io/" # the base hostname & protocol for your site
#permalink: /:year/:month/:day/:title
twitter_username: y.zhao
github_username:  xiaoke0515

# Build settings
#auto: true
markdown: kramdown

# collections
collections:
  tag:
    output: true

