# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Y.L. Zhao
email: ylzhao1996@qq.com
description: > # this means to ignore newlines until "baseurl:"
  My site is built on Nov. 24, 2019. It is used to record something I am interested in.


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xiaoke0515.github.io/" # the base hostname & protocol for your site
#permalink: /:year/:month/:day/:title
twitter_username: y.zhao
github_username:  xiaoke0515

# Build settings
#auto: true
markdown: kramdown

intensedebate_identifier: 1026458b3a9d7f0542e1aa6b86d3ae05

# collections
collections:
  tag:
    output: true

links1:
  - mame:     All
    url:      /categories/
    type:     recent
    esternal: false
  - mame:     jekyll
    url:      /categories/jekyll
    type:     jekyll
    esternal: false
  - mame:     update
    url:      /categories/update
    type:     update
    esternal: false
  - mame:     tensorflow 
    url:      /categories/tensorflow 
    type:     tensorflow 
    esternal: false
  - mame:     ReRAM_paper 
    url:      /categories/ReRAM_paper 
    type:     ReRAM_paper 
    esternal: false
  - mame:     MNN_paper 
    url:      /categories/MNN_paper 
    type:     MNN_paper 
    esternal: false
  - mame:     others  
    url:      /categories/others  
    type:     others  
    esternal: false
  - mame:     IC Design 
    url:      /categories/ICDesign 
    type:     IC  
    esternal: false
  - mame:     GEM5 
    url:      /categories/GEM5 
    type:     GEM5 
    esternal: false

